preload = /home/rbedit7/walls/shocker-clean-1000071808.jpg
#wallpaper = HDMI-A-1,/home/rbedit7/.config/hypr/wallpaper/mima.png
wallpaper = eDP-1,/home/rbedit7/walls/shocker-clean-1000071808.jpg
splash = false
